services:
  vuejs-prod:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-vuejs-sample
    ports:
      - "80:5173"
    command: bash -c "npm i && npm run dev-docker"
    volumes:
      - ./:/app
      - /app/node_modules